- name: Step 8 of 11 -> Fetch CDMS Source Code and Data
  unarchive:
    src: https://github.com/cloudmesh/cloudmesh.cdms/archive/master.zip
    dest: /home/cc
    remote_src: True

- name: Step 9 of 11 -> Compile CDMS Source Code
  shell: source /home/cc/intel/bin/compilervars.sh intel64 && cd /home/cc/cloudmesh.cdms-master/code/trap_analysis && make realclean && make trap_hadoop && make clean && make trap_omp
  args:
     executable: /bin/bash

- name: Step 10 of 11 -> Run CDMS OpenMP Applicaton
  shell: source /home/cc/intel/bin/compilervars.sh intel64 && ulimit -S -s 120000 && export OMP_STACKSIZE=100M && cd /home/cc/cloudmesh.cdms-master/data && /home/cc/cloudmesh.cdms-master/code/trap_analysis/trap_omp
  args:
     executable: /bin/bash

- name: Step 11 of 11 -> Run CDMS Hadoop Applicaton
  shell: sudo su - hadoop && source /home/cc/intel/bin/compilervars.sh intel64 && hadoop fs -mkdir /cdms && hadoop fs -mkdir /cdms/input && hadoop fs -put /home/cc/cloudmesh.cdms-master/data/chA*.dat /cdms/input/ && hadoop jar /opt/hadoop-2.7.1/share/hadoop/tools/lib/hadoop-streaming-2.7.1.jar -D mapreduce.input.fileinputformat.split.minsize=2000000 -input /cdms/input -output /cdms/output -mapper /home/cc/cloudmesh.cdms-master/code/trap_analysis/trap_hadoop -reducer /bin/cat
  args:
     executable: /bin/bash
