- name: Step 8 of 11 -> Download CDMS Data for Simulation
  unarchive:
    src: https://github.com/scottmcclary1/CDMS-Data/archive/master.zip
    dest: /home/cc
    remote_src: True

- name: Step 9 of 11 -> Download CDMS Source Code
  unarchive:
    src: https://github.com/scottmcclary1/CDMS/archive/master.zip
    dest: /home/cc
    remote_src: True

- name: Step 10 of 11 -> Compile CDMS Source Code
  shell: source /home/cc/intel/bin/compilervars.sh intel64 && cd /home/cc/CDMS-master/trap_analysis && make clean && make trap && make clean && make trap_omp
  args:
     executable: /bin/bash

- name: Step 11 of 11 -> Run CDMS Applicaton
  shell: source /home/cc/intel/bin/compilervars.sh intel64 && ulimit -S -s 120000 && export OMP_STACKSIZE=100M && cd /home/cc/CDMS-Data-master && /home/cc/CDMS-master/trap_analysis/trap_omp < /home/cc/CDMS-master/trap_analysis/input.txt 
  args:
     executable: /bin/bash
