---
# tasks file for master

- name: Install add-apt-repostory
  become: yes
  apt: name=software-properties-common state=latest

- name: Add Oracle Java Repository
  become: yes
  apt_repository: repo='ppa:webupd8team/java'

- name: Accept Java 8 License
  become: yes
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Install Oracle Java 8
  become: yes
  apt: name={{item}} state=latest
  with_items:
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default

# Install Hadoop

# this is a bandwidth heavy task which downloads hadoop binaries to each node
- name: Download hadoop
  get_url: url={{ hadoop_download_url }} dest=/home/{{ hadoop_user }}/hadoop-2.7.1.tar.gz
  
- name: Extract hadoop archive
  unarchive: src=/home/{{ hadoop_user }}/hadoop-2.7.1.tar.gz dest=/home/{{ hadoop_user }} owner={{ hadoop_user}} group={{ hadoop_group }} creates=/usr/local/hadoop copy=no
  

- file: path=/home/{{ hadoop_user }}/tmp state=directory owner={{ hadoop_user}} group={{ hadoop_group }} mode=750
- file: path=/home/{{ hadoop_user }}/hadoop-data/hdfs/namenode state=directory owner={{ hadoop_user}} group={{ hadoop_group }} mode=750
- file: path=/home/{{ hadoop_user }}/hadoop-data/hdfs/datanode state=directory owner={{ hadoop_user}} group={{ hadoop_group }} mode=750

- name: Add the service scripts
  template: src={{ item.src }} dest={{ item.dest }} owner={{ hadoop_user}} group={{ hadoop_group }}
  with_items:
    - {src: "core-site.xml", dest: "{{ hadoop_home }}/etc/hadoop/core-site.xml"}
    - {src: "hdfs-site.xml", dest: "{{ hadoop_home }}/etc/hadoop/hdfs-site.xml"}
    - {src: "yarn-site.xml", dest: "{{ hadoop_home }}/etc/hadoop/yarn-site.xml"}
    - {src: "mapred-site.xml", dest: "{{ hadoop_home }}/etc/hadoop/mapred-site.xml"}

- lineinfile: dest={{ hadoop_home }}/etc/hadoop/hadoop-env.sh regexp="^export JAVA_HOME" line="export JAVA_HOME=/usr/lib/jvm/java-8-oracle"
