---
- hosts: all
  become: true
  vars:
    ubuntu_user_name: cc
  roles:
    - chameleon_setup

- hosts: master
  become: true
  vars:
    ubuntu_user_name: cc
  roles:
    - chameleon_ben1

- hosts: master
  become: true
  vars:
    ubuntu_user_name: cc
  roles:
    - chameleon_ben2

- hosts: master
  become: true
  vars:
    ubuntu_user_name: cc
  roles:
    - chameleon_ben3

- hosts: master
  remote_user: true
  roles:
   - ansible-node

